### PR TITLE
Added auto-schema naming option.

### PR DESCRIPTION
**Pull request by baallan**
Code, test, and man page nit cleanup.
Got rid of redundant/unused definitions.
Got rid of extra debug statements.
Reordered functions to reduce forward definitions needed.
Fixed visual misalignment of braces.
Added test of all schema permutations.
Fixed include of cli .c file.

### CODE REVIEW

**Comment by baallan** [comment]
@Snell1224 in addition to the cleanups in this commit, we need to go over the assignment and usage of the pidopts variable.
When that is done, then the exit() call may be removed, which would be good. Plugins should not call exit.

**Comment by spwalto** [comment]
@baallan I looked into this a bit more and it appears that the pidopts is not necessary. When first starting to code the tx2mon sampler, I was referring to the dstat.c file to help me figure out how to do the struct mapping. The version of this dstat.c file (in this tx2mon repo) was using the "pidopts" variable for multiple structs (PID_IO, PID_STAT, PIDSTATM) to include (or not include) their data in the output.

Since the tx2mon sampler is only pulling data from a single struct (mc_oper_region.h) then there's no need for it. I've removed it and the code built and successfully ran with ldms-static-test.

As for the exit (1):
I returned the value of "EINVAL" because the config function will return an error if "create_metric_set" is not zero (lines 522-526 in tx2mon.c) and EINVAL has a value of 22.

I've updated these change in this repo. Please let me know if there is anything else that needs to be changed and/or discussed. Also thank you very much for cleaning up the code and manpages!

**Comment by baallan** [comment]
Looks like since

MC_OPER_REGION is a constant, any if() logic dependent on it can be simplified out/de-indented.

gcc should have whined about that.


Ben

________________________________

**Comment by spwalto** [comment]
@baallan Interesting because I didn't see/get any warning messages about it. Compiled with make install/make check and the various -g O# flags listed in the gitlab issue.....
At any rate, I still removed the MC_OPER_REGION if statements because you're right, since it's a constant there's no need to do any checks with it. 
The sampler worked and compiled successfully without any complaints and changes have been pushed to this repo.

**Comment by baallan** [comment]
I see elsewhere it looks like gcc dropped this warning after about version 4.4. most unfortunate.
If the macro is always true, and if after you simplify all the logic that depends on that then there are no uses of it left, then it’s safe (and a good idea) to get rid of the macro.

Did it ever do anything useful in the original CLI? Or was it just cruft there too?

ben

**Comment by spwalto** [comment]
Okay, none of the code depended on it (other than checking if it was valid which was always true) and the macro was never changed so I had it removed. And no, the macro wasn't used at all in the original CLI. It was all from the dstat.c sampler code. 
I've compiled and checked the code with the ldms-static-test without any issues/errors.

**Pull request merged**
